# Generated by Django 3.2.5 on 2023-04-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sulg',
            new_name='slug',
        ),
    ]
